apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      my-label: some-value
  replicas: 3
  template: 
    metadata:
      name: project
      labels:
        my-label: some-value
    spec: 
      containers:
        - image: os2023/salma1
          name: deployment-container
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"